### PR TITLE
Update to angular 9

### PR DESCRIPTION
**Pull request by DanielHabenicht**
Faster Builds!  (Just 76s!) (in the future also only one build instead of 2)
Smaller Files (~20%)
Better translation coming (just not yet, angular team still need time https://github.com/angular/angular-cli/issues/16375) 

Till then: 
- [x] Update Docs to incorporate a new way of localization
- [x] Change Build and delivery of multi-lang phonebook 
- [x] New Issue for tackling `TODO: Localization` --> #515 
- [x] Fix xlf file generation https://github.com/loclapp/locl/tree/master/libs/core
- [x] Maybe fix failing tests
- [x] Issue for updating localization after angular https://github.com/angular/angular/pull/32912 goes through --> #516

### CODE REVIEW

**Comment by Zeroks77** [comment]
🤯🤯 Angular 9

**Comment by DanielHabenicht** [comment]
@T-Systems-MMS/phonebook-developers would you take a look if everything is still working?

**Comment by Zeroks77** [comment]
image
found something :D 
think he shouldnt be empty

**Comment by DanielHabenicht** [comment]
Thats not a problem of this PR but a general Problem. You can find the same problem in the main demo.

**Comment by DanielHabenicht** [comment]
@Zeroks77 approve?

**Comment by marcuskrahl** [comment]
I had a look at every commit except for the one with 15k lines changed for localization. 
Looks all good to me.

**Pull request merged**
