### PR TITLE
fix(user-detail): too much whitespace 

### LINKED ISSUE #459: User-Detail-Page: large white space under contact information in firefox & edge
**Describe the bug:**

Large white space under contact information in firefox and edge.
image

It looks like that the problem only occurs if a roomplan is loaded!

**To Reproduce:**

-> Go to a user in phonebook in firefox or edge. https://demo-phonebook.me/en/user/H5QX

**Expected behavior:**

Like it ever was:
image

**Additional context:**
Firefox 68.2.0esr (64-Bit)
Microsoft Edge 44.17763.831.0

### PR DESCRIPTION
**Pull request by mschwrdtnr**
fixes #459 

I thought the class overrides should be in but they were the reason for the error. Please have a look, test it in different browsers. For me everything works in edge, firefox, chrome.

### CODE REVIEW

**Comment by DanielHabenicht** [comment]
But it reintroduces the bug from before: 
image
The buttons are not at the bottom anymore

**Comment by mschwrdtnr** [comment]
Oh, didn't saw this. I thought i can fix this problem fast because the big impact. I will try to find time for this the next days...

**Comment by DanielHabenicht** [comment]
Yeah, Azure Pipelines has updated chrome again...
Have a look at the `.pb-expand` in the `user-detail.component` the `height` property seems to cause the problem.

**Comment by mschwrdtnr** [comment]
Looks good for me @DanielHabenicht

**Pull request merged**
