### PR TITLE
fix the orgdiagramm bug

### PR DESCRIPTION
**Pull request by paule96**

### CODE REVIEW

**Comment by DanielHabenicht** [comment]
What does it do?

**Comment by paule96** [comment]
It fixes the old data structure.
So a owner of an org unit is also in its own org unit. So if you try to get the super visor of an owner it will be an self reference. So semthing like this:

Klaus = Orgunit A
Owner Of Orgunit A = Klaus

The owner of Klaus is Klaus because Klaus is member of Org Unit A and the Super visor of Orgunit A is Klaus...

But this is wrong. The super visor of Claus is Peter because Peter is owner of Orgunit B and Orgunit A is Member of Orgunit B.

**Comment by DanielHabenicht** [comment]
So this is the state your code is in now: "The super visor of Claus is Peter because Peter is owner of Orgunit B and Orgunit A is Member of Orgunit B." 

Does this also reflect in the mock data?

**Comment by paule96** [comment]
Yes 👍 

It's not effected by this :)

**Pull request merged**
