### PR TITLE
chore(folders): move folder for clarity

### LINKED ISSUE #430: Chore: Naming and folders
We should move all demo things into a demo folder. That means
BEFORE:
```
📦Repo
 ┣ 📂Phonebook.Assets
 ┣ 📂Phonebook.Demo
 ┣ 📂Phonebook.Frontend
 ┣ 📂Phonebook.Source.MockPeopleBackend
 ┣ 📂Phonebook.Source.PeopleSoft
 ┣ 📂Phonebook
 ┣ 📂docs
```

AFTER
```
📦Repo
 ┣ 📂Phonebook.Frontend
 ┣ 📂Phonebook.Source.PeopleSoft
 ┣ 📂Phonebook
 ┣ 📂demo
 ┃ ┗ 📜assets
 ┃ ┗ 📜source (previously MockPeopleBackend)
 ┃ ┗ 📜Current Phonebook.Demo Content
 ┣ 📂docs
```
What do you guys think? @T-Systems-MMS/phonebook-developers

### PR DESCRIPTION
**Pull request by DanielHabenicht**
closes #430

### CODE REVIEW

**Comment by DanielHabenicht** [comment]
Should we also rename `source` to `dataSource`?

@paule96 should I adhere to the standard of the .net Project and make it `Demo.Assets` and so on?

**Comment by paule96** [comment]
first I would create a `src` folder for `Phonebook.Frontend` and `Phonebook.Source.PeopleSoft`. 

also I would rename the folder `Phonebook` to `scripts` or `hosting`or something like this. Because there is all the operational stuff in it.

But this is maybe another issue. This is currently only for demo. So we should only look at demo. To this I will create an issue if it not exsists already.

**Comment by paule96** [comment]
> Should we also rename source to dataSource?
> @paule96 should I adhere to the standard of the .net Project and make it Demo.Assets and so on?

no not in this PR. the issue was explicit only for demo.

**Comment by DanielHabenicht** [comment]
> first I would create a `src` folder for `Phonebook.Frontend` and `Phonebook.Source.PeopleSoft`.

Ok I will go forward and create a src folder 

> also I would rename the folder `Phonebook` to `scripts` or `hosting`or something like this. Because there is all the operational stuff in it.

Yep, how about `helm`?

> But this is maybe another issue. This is currently only for demo. So we should only look at demo. To this I will create an issue if it not exsists already.

**Comment by paule96** [comment]
> first I would create a src folder for Phonebook.Frontend and Phonebook.Source.PeopleSoft.
> 
> Ok I will go forward and create a src folder
> 
> also I would rename the folder Phonebook to scripts or hostingor something like this. Because there is all the operational stuff in it.
> 
> Yep, how about helm?
> 
> But this is maybe another issue. This is currently only for demo. So we should only look at demo. To this I will create an issue if it not exsists already.

helm is a product name. not a thing you can do or understand. So it isn't a good name. You describe what the folder contains or what you can do with it. Not what product you must install to use it 🤷‍♀️

**Comment by DanielHabenicht** [comment]
> > first I would create a src folder for Phonebook.Frontend and Phonebook.Source.PeopleSoft.
> > Ok I will go forward and create a src folder
> > also I would rename the folder Phonebook to scripts or hostingor something like this. Because there is all the operational stuff in it.
> > Yep, how about helm?
> > But this is maybe another issue. This is currently only for demo. So we should only look at demo. To this I will create an issue if it not exsists already.
> 
> helm is a product name. not a thing you can do or understand. So it isn't a good name. You describe what the folder contains or what you can do with it. Not what product you must install to use it 🤷‍♀️

`helm-chart` then?

**Comment by paule96** [comment]
> first I would create a src folder for Phonebook.Frontend and Phonebook.Source.PeopleSoft.
> Ok I will go forward and create a src folder
> also I would rename the folder Phonebook to scripts or hostingor something like this. Because there is all the operational stuff in it.
> Yep, how about helm?
> But this is maybe another issue. This is currently only for demo. So we should only look at demo. To this I will create an issue if it not exsists already.
> 
> helm is a product name. not a thing you can do or understand. So it isn't a good name. You describe what the folder contains or what you can do with it. Not what product you must install to use it 🤷‍♀️
> 
> helm-chart then?

no. What does the folder do? or for what kind of people is it for. Think this way. not in product. 
Helm chart, is the same like PowerShell script. that can do all and nothing. What does the stuff do. Maybe we call it `install` or so. Or `setup`. or `operational`

**Comment by DanielHabenicht** [comment]
Discussion of `src` folder is now here: #507 

This PR is now only about moving the demo folders

**Pull request merged**
