### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by mschwrdtnr**
I prepared the default issue templates for feature requests and bug reports.

### CODE REVIEW

**Comment by DanielHabenicht** [comment]
Maybe there should be a note about this being a public Issue tracker. 
We should also point out that screenshots should not contain any personal information.

**Comment by mschwrdtnr** [comment]
Where would be the best place for this information? At the beginning?

**Comment by DanielHabenicht** [comment]
The note should be at the beginning and the other one right when the template suggests to upload a picture.

**Comment by mschwrdtnr** [comment]
Is it possible to notificate a user after a file attachment? Can't find something about..

**Comment by DanielHabenicht** [comment]
No but just prepend it to sentence.. (Please pay attention to not disclose personal information)

Cheers
Daniel

________________________________

**Comment by DanielHabenicht** [comment]
Can you comment out the tips in order for them to be not displayed in the issue once filled out.

**Comment by mschwrdtnr** [comment]
I didn't uncomment the warnings for better readability. the other things should be fine.

**Pull request merged**
